### ISSUE TITLE
5x 60seconde metingen voor phase plots

### ISSUE THREAD

**Issue by Nynra** [Nynra/pohls_pendulum#62]

**Comment by Doekwan** [comment]
Pendulum word stil gehouden tot de meting start

metingen uitgevoerd zonder demping bij 24V
- meting 1: 24V 0.620A
- meting 2: 24V 0.600A
- meting 3: 24V 0.550A
- meting 4: 24V 0.500A
- meting 5: 24V 0.450A
- meting 6: 24V 0.400A
- meting 7: 24V 0.350A
- meting 8: 24V 0.300A
- meting 9: 24V 0.250A

**Comment by Doekwan** [comment]
MEting 5min: 24V 0.420A

**Comment by Doekwan** [comment]
Meting 10: 24V 0.475A
Meting 11: 24V 0.440A

**Comment by Doekwan** [comment]
Meting 5min: 24V 0.425A
Meting 5min: 24V 0.410A

**Comment by Doekwan** [comment]
Meting 5min: 24V 0.400A

**Comment by Doekwan** [comment]
Meting 10min: 24V 0.405A
